source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'ICETutorial'
pod 'IHKeyboardAvoiding'
pod 'ActionSheetPicker-3.0', '~> 1.3.9'
pod 'RMDateSelectionViewController'
pod 'pop', '~> 1.0'
pod 'SGNavigationProgress'
pod 'PPiFlatSegmentedControl'
pod 'SDWebImage', '~>3.6'
